### ISSUE TITLE
-r Value Error

### ISSUE THREAD

**Issue by L-HeliantHuS** [AngelKitty/stegosaurus#1]
```python
root@Kali:~/ctf/misc/stegosaurus# python3 stegosaurus.py example.py -r
Traceback (most recent call last):
  File "stegosaurus.py", line 251, in <module>
    main()
  File "stegosaurus.py", line 217, in main
    header, code = _loadBytecode(carrier, logger)
  File "stegosaurus.py", line 124, in _loadBytecode
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

进行-r参数的时候出现Error.

**Comment by AngelKitty** [comment]
@L-HeliantHuS 您可以直接用打包好的bin文件

**Comment by AngelKitty** [comment]
@L-HeliantHuS 刚发布了release，你可以直接下载bin文件使用，用法一样，直接运行bin文件就行了

**Comment by AngelKitty** [comment]
@L-HeliantHuS 
![屏幕截图](https://user-images.githubusercontent.com/30405643/69949780-1fd53700-152d-11ea-8df0-f84d5ddb01c1.png)

**Comment by L-HeliantHuS** [comment]
好的可以了！ 成功解决。

**Comment by liguodong4624** [comment]
![image](https://user-images.githubusercontent.com/56248620/76833485-65143f00-6866-11ea-8db0-2dca1ab0babd.png)
请问这种情况删除哪个包下的pyc？

**Comment by AngelKitty** [comment]
@liguodong4624 您就直接使用我打包好的release包吧

**Comment by AngelKitty** [comment]
@liguodong4624 我刚才看了一下，应该是python版本的问题，python3.6是没有问题的
